name: Compile omniedge for openwrt

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    name: Build - ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arch: "arm_cortex-a7_neon-vfpv4"
            sdk: "https://archive.openwrt.org/releases/21.02.3/targets/ipq40xx/generic/openwrt-sdk-21.02.3-ipq40xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz"
          - arch: "arm_cortex-a8_vfpv3"
            sdk: "https://downloads.openwrt.org/releases/21.02.3/targets/sunxi/cortexa8/openwrt-sdk-21.02.3-sunxi-cortexa8_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz"
          - arch: "arm_cortex-a15_neon-vfpv4"
            sdk: "https://downloads.openwrt.org/releases/21.02.3/targets/ipq806x/generic/openwrt-sdk-21.02.3-ipq806x-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz"
    steps:
      - uses: actions/checkout@v2
      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential autoconf openssl gzip libssl-dev zip upx -y 

      - name: Install OpenWrt SDK
        run: |
          wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
          mv -f openwrt-sdk-* openwrt-sdk    
      - name: Build Package
        run: |
          echo "src-link omniedge $GITHUB_WORKSPACE" > openwrt-sdk/feeds.conf
          echo 'CONFIG_PACKAGE_omniedge=y
          ' >> openwrt-sdk/.config
          cd openwrt-sdk
          cat feeds.conf.default >> feeds.conf
          cat feeds.conf

          ./scripts/feeds update -a -f > /dev/null
          make defconfig

          ./scripts/feeds install -d y -f -a
          make package/omniedge/compile V=s
          tree bin/packages/
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: omniedge-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/omniedge/omniedge*.ipk
          if-no-files-found: error
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        # if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: openwrt-sdk/bin/packages/*/omniedge/omniedge*.ipk
          tag: ${{ github.ref }}
