name: Compile omniedge for openwrt

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    name: Build - ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arch: "arm_cortex-a7_neon-vfpv4"
            sdk: "https://downloads.openwrt.org/releases/22.03.0-rc5/targets/ipq40xx/generic/openwrt-sdk-22.03.0-rc5-ipq40xx-generic_gcc-11.2.0_musl_eabi.Linux-x86_64.tar.xz"
    steps:
      - uses: actions/checkout@v2
      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf openssl gzip libssl-dev zip upx

      - name: Install OpenWrt SDK
        run: |
          wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
          mv -f openwrt-sdk-* openwrt-sdk
      - name: Prepare Environment Variable
        run: |
          export TARGET_CC=./openwrt-sdk/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/bin/arm-openwrt-linux-gcc
          export TARGET_CXX=./openwrt-sdk/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.2.0_musl_eabi/bin/arm-openwrt-linux-g++
          export CGO_ENABLED=1 
          export GOOS=linux 
          export GOARCH=arm
          
      - name: Build Package
        run: |
          echo "src-link omniedge $GITHUB_WORKSPACE" > openwrt-sdk/feeds.conf
          echo 'CONFIG_PACKAGE_omniedge=y
          ' >> openwrt-sdk/.config
          cd openwrt-sdk
          cat feeds.conf.default >> feeds.conf
          cat feeds.conf

          ./scripts/feeds update -a > /dev/null
          make defconfig

          ./scripts/feeds install -d y -f -a
          make package/omniedge/compile V=s
          tree bin/packages/
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: omniedge-${{ matrix.target.arch }}
          path: openwrt-sdk/bin/packages/*/omniedge/omniedge*.ipk
          if-no-files-found: error
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: openwrt-sdk/bin/packages/*/omniedge/omniedge*.ipk
          tag: ${{ github.ref }}
